# version: '3.1'
services:

  profetisa:
    image: profetisa
    container_name: profetisa
    build:
      context: profetisa
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: profetisa/src
    ports:
      - 8001:8001
    volumes:
      - ${PWD}/profetisa/model/openhermes-2.5-mistral-7b.Q4_K_M.gguf:/code/model/openhermes-2.5-mistral-7b.Q4_K_M.gguf
    networks:
      - claudia-network

  embedder:
    image: embedder
    container_name: embedder
    build:
      context: embeddings
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - claudia-network
    depends_on:
      - qdrant

  front:
    image: claudia-front
    container_name: claudia-front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 8080:8080
    networks:
      - claudia-network
    depends_on:
      - embedder
      - profetisa

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - claudia-network

configs:
  qdrant_config:
    content: |
      log_level: INFO      

networks: 
    claudia-network:
      driver: bridge